/*
 * Goddard.ToursWebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AvailabilityInputDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailabilityInputDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailabilityInputDto
        //private AvailabilityInputDto instance;

        public AvailabilityInputDtoTests()
        {
            // TODO uncomment below to create an instance of AvailabilityInputDto
            //instance = new AvailabilityInputDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailabilityInputDto
        /// </summary>
        [Fact]
        public void AvailabilityInputDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvailabilityInputDto
            //Assert.IsType<AvailabilityInputDto>(instance);
        }


        /// <summary>
        /// Test the property 'Blocks'
        /// </summary>
        [Fact]
        public void BlocksTest()
        {
            // TODO unit test for the property 'Blocks'
        }

    }

}
