/*
 * Goddard.ToursWebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DefaultTourDurationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DefaultTourDurationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DefaultTourDurationDto
        //private DefaultTourDurationDto instance;

        public DefaultTourDurationDtoTests()
        {
            // TODO uncomment below to create an instance of DefaultTourDurationDto
            //instance = new DefaultTourDurationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultTourDurationDto
        /// </summary>
        [Fact]
        public void DefaultTourDurationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DefaultTourDurationDto
            //Assert.IsType<DefaultTourDurationDto>(instance);
        }


        /// <summary>
        /// Test the property 'TourSettingsId'
        /// </summary>
        [Fact]
        public void TourSettingsIdTest()
        {
            // TODO unit test for the property 'TourSettingsId'
        }
        /// <summary>
        /// Test the property 'SchoolId'
        /// </summary>
        [Fact]
        public void SchoolIdTest()
        {
            // TODO unit test for the property 'SchoolId'
        }
        /// <summary>
        /// Test the property 'DefaultTourDuration'
        /// </summary>
        [Fact]
        public void DefaultTourDurationTest()
        {
            // TODO unit test for the property 'DefaultTourDuration'
        }

    }

}
