/*
 * Goddard.ToursWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduleItemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleItemDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduleItemDto
        //private ScheduleItemDto instance;

        public ScheduleItemDtoTests()
        {
            // TODO uncomment below to create an instance of ScheduleItemDto
            //instance = new ScheduleItemDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduleItemDto
        /// </summary>
        [Fact]
        public void ScheduleItemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduleItemDto
            //Assert.IsType<ScheduleItemDto>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'StartLocalDateTime'
        /// </summary>
        [Fact]
        public void StartLocalDateTimeTest()
        {
            // TODO unit test for the property 'StartLocalDateTime'
        }
        /// <summary>
        /// Test the property 'EndLocalDateTime'
        /// </summary>
        [Fact]
        public void EndLocalDateTimeTest()
        {
            // TODO unit test for the property 'EndLocalDateTime'
        }

    }

}
