/*
 * Goddard.ToursWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduleItemTourTypeDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleItemTourTypeDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduleItemTourTypeDto
        //private ScheduleItemTourTypeDto instance;

        public ScheduleItemTourTypeDtoTests()
        {
            // TODO uncomment below to create an instance of ScheduleItemTourTypeDto
            //instance = new ScheduleItemTourTypeDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduleItemTourTypeDto
        /// </summary>
        [Fact]
        public void ScheduleItemTourTypeDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduleItemTourTypeDto
            //Assert.IsType<ScheduleItemTourTypeDto>(instance);
        }


        /// <summary>
        /// Test the property 'TourType'
        /// </summary>
        [Fact]
        public void TourTypeTest()
        {
            // TODO unit test for the property 'TourType'
        }
        /// <summary>
        /// Test the property 'SlotsAvailable'
        /// </summary>
        [Fact]
        public void SlotsAvailableTest()
        {
            // TODO unit test for the property 'SlotsAvailable'
        }
        /// <summary>
        /// Test the property 'AttendeeCount'
        /// </summary>
        [Fact]
        public void AttendeeCountTest()
        {
            // TODO unit test for the property 'AttendeeCount'
        }

    }

}
