/*
 * Goddard.ToursWebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SchoolTourAvailabilityDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchoolTourAvailabilityDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchoolTourAvailabilityDto
        //private SchoolTourAvailabilityDto instance;

        public SchoolTourAvailabilityDtoTests()
        {
            // TODO uncomment below to create an instance of SchoolTourAvailabilityDto
            //instance = new SchoolTourAvailabilityDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchoolTourAvailabilityDto
        /// </summary>
        [Fact]
        public void SchoolTourAvailabilityDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchoolTourAvailabilityDto
            //Assert.IsType<SchoolTourAvailabilityDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SchoolId'
        /// </summary>
        [Fact]
        public void SchoolIdTest()
        {
            // TODO unit test for the property 'SchoolId'
        }
        /// <summary>
        /// Test the property 'DayOfWeek'
        /// </summary>
        [Fact]
        public void DayOfWeekTest()
        {
            // TODO unit test for the property 'DayOfWeek'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'TourTypes'
        /// </summary>
        [Fact]
        public void TourTypesTest()
        {
            // TODO unit test for the property 'TourTypes'
        }

    }

}
