/*
 * Goddard.ToursWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TourDtoPaginationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TourDtoPaginationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TourDtoPaginationDto
        //private TourDtoPaginationDto instance;

        public TourDtoPaginationDtoTests()
        {
            // TODO uncomment below to create an instance of TourDtoPaginationDto
            //instance = new TourDtoPaginationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TourDtoPaginationDto
        /// </summary>
        [Fact]
        public void TourDtoPaginationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TourDtoPaginationDto
            //Assert.IsType<TourDtoPaginationDto>(instance);
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
