/*
 * Goddard.ToursWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TourSettingsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TourSettingsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TourSettingsDto
        //private TourSettingsDto instance;

        public TourSettingsDtoTests()
        {
            // TODO uncomment below to create an instance of TourSettingsDto
            //instance = new TourSettingsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TourSettingsDto
        /// </summary>
        [Fact]
        public void TourSettingsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TourSettingsDto
            //Assert.IsType<TourSettingsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SchoolId'
        /// </summary>
        [Fact]
        public void SchoolIdTest()
        {
            // TODO unit test for the property 'SchoolId'
        }
        /// <summary>
        /// Test the property 'MaxOpenHouseParticipants'
        /// </summary>
        [Fact]
        public void MaxOpenHouseParticipantsTest()
        {
            // TODO unit test for the property 'MaxOpenHouseParticipants'
        }

    }

}
