/*
 * Goddard.ToursWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ToursWebApiClient.Api;
using FranchiseePortal.ToursWebApiClient.Model;
using FranchiseePortal.ToursWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ToursWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TourStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TourStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TourStatus
        //private TourStatus instance;

        public TourStatusTests()
        {
            // TODO uncomment below to create an instance of TourStatus
            //instance = new TourStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TourStatus
        /// </summary>
        [Fact]
        public void TourStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" TourStatus
            //Assert.IsType<TourStatus>(instance);
        }



    }

}
