/*
 * Goddard.FMS.SchoolEvents
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using FranchiseePortal.SchoolEventsWebApiClient.Client;
using FranchiseePortal.SchoolEventsWebApiClient.Model;

namespace FranchiseePortal.SchoolEventsWebApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <returns>PostEvents</returns>
        PostEvents ApiV1AddEventsPost(PostEvents postEvents = default(PostEvents));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <returns>ApiResponse of PostEvents</returns>
        ApiResponse<PostEvents> ApiV1AddEventsPostWithHttpInfo(PostEvents postEvents = default(PostEvents));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <returns>List&lt;Events&gt;</returns>
        List<Events> ApiV1EventsGet(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <returns>ApiResponse of List&lt;Events&gt;</returns>
        ApiResponse<List<Events>> ApiV1EventsGetWithHttpInfo(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PostEvents</returns>
        System.Threading.Tasks.Task<PostEvents> ApiV1AddEventsPostAsync(PostEvents postEvents = default(PostEvents), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PostEvents)</returns>
        System.Threading.Tasks.Task<ApiResponse<PostEvents>> ApiV1AddEventsPostWithHttpInfoAsync(PostEvents postEvents = default(PostEvents), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Events&gt;</returns>
        System.Threading.Tasks.Task<List<Events>> ApiV1EventsGetAsync(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Events&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Events>>> ApiV1EventsGetWithHttpInfoAsync(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApi : IEventsApiSync, IEventsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EventsApi : IEventsApi
    {
        private FranchiseePortal.SchoolEventsWebApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EventsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EventsApi(String basePath)
        {
            this.Configuration = FranchiseePortal.SchoolEventsWebApiClient.Client.Configuration.MergeConfigurations(
                FranchiseePortal.SchoolEventsWebApiClient.Client.GlobalConfiguration.Instance,
                new FranchiseePortal.SchoolEventsWebApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new FranchiseePortal.SchoolEventsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new FranchiseePortal.SchoolEventsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = FranchiseePortal.SchoolEventsWebApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EventsApi(FranchiseePortal.SchoolEventsWebApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = FranchiseePortal.SchoolEventsWebApiClient.Client.Configuration.MergeConfigurations(
                FranchiseePortal.SchoolEventsWebApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new FranchiseePortal.SchoolEventsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new FranchiseePortal.SchoolEventsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = FranchiseePortal.SchoolEventsWebApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EventsApi(FranchiseePortal.SchoolEventsWebApiClient.Client.ISynchronousClient client, FranchiseePortal.SchoolEventsWebApiClient.Client.IAsynchronousClient asyncClient, FranchiseePortal.SchoolEventsWebApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = FranchiseePortal.SchoolEventsWebApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public FranchiseePortal.SchoolEventsWebApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public FranchiseePortal.SchoolEventsWebApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public FranchiseePortal.SchoolEventsWebApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public FranchiseePortal.SchoolEventsWebApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <returns>PostEvents</returns>
        public PostEvents ApiV1AddEventsPost(PostEvents postEvents = default(PostEvents))
        {
            FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<PostEvents> localVarResponse = ApiV1AddEventsPostWithHttpInfo(postEvents);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <returns>ApiResponse of PostEvents</returns>
        public FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<PostEvents> ApiV1AddEventsPostWithHttpInfo(PostEvents postEvents = default(PostEvents))
        {
            FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions localVarRequestOptions = new FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = postEvents;


            // make the HTTP request
            var localVarResponse = this.Client.Post<PostEvents>("/api/v1/addEvents", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1AddEventsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PostEvents</returns>
        public async System.Threading.Tasks.Task<PostEvents> ApiV1AddEventsPostAsync(PostEvents postEvents = default(PostEvents), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<PostEvents> localVarResponse = await ApiV1AddEventsPostWithHttpInfoAsync(postEvents, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postEvents"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PostEvents)</returns>
        public async System.Threading.Tasks.Task<FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<PostEvents>> ApiV1AddEventsPostWithHttpInfoAsync(PostEvents postEvents = default(PostEvents), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions localVarRequestOptions = new FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = postEvents;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PostEvents>("/api/v1/addEvents", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1AddEventsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <returns>List&lt;Events&gt;</returns>
        public List<Events> ApiV1EventsGet(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string))
        {
            FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<List<Events>> localVarResponse = ApiV1EventsGetWithHttpInfo(fmsSchoolId, startDate, endDate);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <returns>ApiResponse of List&lt;Events&gt;</returns>
        public FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<List<Events>> ApiV1EventsGetWithHttpInfo(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string))
        {
            FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions localVarRequestOptions = new FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (fmsSchoolId != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "fmsSchoolId", fmsSchoolId));
            }
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Events>>("/api/v1/events", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1EventsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Events&gt;</returns>
        public async System.Threading.Tasks.Task<List<Events>> ApiV1EventsGetAsync(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<List<Events>> localVarResponse = await ApiV1EventsGetWithHttpInfoAsync(fmsSchoolId, startDate, endDate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolEventsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fmsSchoolId"> (optional)</param>
        /// <param name="startDate"> (optional)</param>
        /// <param name="endDate"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Events&gt;)</returns>
        public async System.Threading.Tasks.Task<FranchiseePortal.SchoolEventsWebApiClient.Client.ApiResponse<List<Events>>> ApiV1EventsGetWithHttpInfoAsync(string fmsSchoolId = default(string), string startDate = default(string), string endDate = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions localVarRequestOptions = new FranchiseePortal.SchoolEventsWebApiClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (fmsSchoolId != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "fmsSchoolId", fmsSchoolId));
            }
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolEventsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Events>>("/api/v1/events", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1EventsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
