/*
 * Goddard iPaaS Schools API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using FranchiseePortal.SchoolsWebApiClient.Client;
using FranchiseePortal.SchoolsWebApiClient.Model;

namespace FranchiseePortal.SchoolsWebApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGeocoordinatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;SchoolGeocoordinate&gt;</returns>
        List<SchoolGeocoordinate> ApiV1GeocoordinatesGet(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;SchoolGeocoordinate&gt;</returns>
        ApiResponse<List<SchoolGeocoordinate>> ApiV1GeocoordinatesGetWithHttpInfo(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGeocoordinatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchoolGeocoordinate&gt;</returns>
        System.Threading.Tasks.Task<List<SchoolGeocoordinate>> ApiV1GeocoordinatesGetAsync(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchoolGeocoordinate&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SchoolGeocoordinate>>> ApiV1GeocoordinatesGetWithHttpInfoAsync(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGeocoordinatesApi : IGeocoordinatesApiSync, IGeocoordinatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GeocoordinatesApi : IGeocoordinatesApi
    {
        private FranchiseePortal.SchoolsWebApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GeocoordinatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GeocoordinatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeocoordinatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GeocoordinatesApi(string basePath)
        {
            this.Configuration = FranchiseePortal.SchoolsWebApiClient.Client.Configuration.MergeConfigurations(
                FranchiseePortal.SchoolsWebApiClient.Client.GlobalConfiguration.Instance,
                new FranchiseePortal.SchoolsWebApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new FranchiseePortal.SchoolsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new FranchiseePortal.SchoolsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = FranchiseePortal.SchoolsWebApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeocoordinatesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GeocoordinatesApi(FranchiseePortal.SchoolsWebApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = FranchiseePortal.SchoolsWebApiClient.Client.Configuration.MergeConfigurations(
                FranchiseePortal.SchoolsWebApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new FranchiseePortal.SchoolsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new FranchiseePortal.SchoolsWebApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = FranchiseePortal.SchoolsWebApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeocoordinatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public GeocoordinatesApi(FranchiseePortal.SchoolsWebApiClient.Client.ISynchronousClient client, FranchiseePortal.SchoolsWebApiClient.Client.IAsynchronousClient asyncClient, FranchiseePortal.SchoolsWebApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = FranchiseePortal.SchoolsWebApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public FranchiseePortal.SchoolsWebApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public FranchiseePortal.SchoolsWebApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public FranchiseePortal.SchoolsWebApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public FranchiseePortal.SchoolsWebApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;SchoolGeocoordinate&gt;</returns>
        public List<SchoolGeocoordinate> ApiV1GeocoordinatesGet(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0)
        {
            FranchiseePortal.SchoolsWebApiClient.Client.ApiResponse<List<SchoolGeocoordinate>> localVarResponse = ApiV1GeocoordinatesGetWithHttpInfo(showOnPublicWebsite);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;SchoolGeocoordinate&gt;</returns>
        public FranchiseePortal.SchoolsWebApiClient.Client.ApiResponse<List<SchoolGeocoordinate>> ApiV1GeocoordinatesGetWithHttpInfo(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0)
        {
            FranchiseePortal.SchoolsWebApiClient.Client.RequestOptions localVarRequestOptions = new FranchiseePortal.SchoolsWebApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = FranchiseePortal.SchoolsWebApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = FranchiseePortal.SchoolsWebApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (showOnPublicWebsite != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "showOnPublicWebsite", showOnPublicWebsite));
            }

            localVarRequestOptions.Operation = "GeocoordinatesApi.ApiV1GeocoordinatesGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("Ocp-Apim-Subscription-Key", this.Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<SchoolGeocoordinate>>("/api/v1/geocoordinates", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1GeocoordinatesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;SchoolGeocoordinate&gt;</returns>
        public async System.Threading.Tasks.Task<List<SchoolGeocoordinate>> ApiV1GeocoordinatesGetAsync(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            FranchiseePortal.SchoolsWebApiClient.Client.ApiResponse<List<SchoolGeocoordinate>> localVarResponse = await ApiV1GeocoordinatesGetWithHttpInfoAsync(showOnPublicWebsite, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="FranchiseePortal.SchoolsWebApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="showOnPublicWebsite"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;SchoolGeocoordinate&gt;)</returns>
        public async System.Threading.Tasks.Task<FranchiseePortal.SchoolsWebApiClient.Client.ApiResponse<List<SchoolGeocoordinate>>> ApiV1GeocoordinatesGetWithHttpInfoAsync(bool? showOnPublicWebsite = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            FranchiseePortal.SchoolsWebApiClient.Client.RequestOptions localVarRequestOptions = new FranchiseePortal.SchoolsWebApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = FranchiseePortal.SchoolsWebApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = FranchiseePortal.SchoolsWebApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (showOnPublicWebsite != null)
            {
                localVarRequestOptions.QueryParameters.Add(FranchiseePortal.SchoolsWebApiClient.Client.ClientUtils.ParameterToMultiMap("", "showOnPublicWebsite", showOnPublicWebsite));
            }

            localVarRequestOptions.Operation = "GeocoordinatesApi.ApiV1GeocoordinatesGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("Ocp-Apim-Subscription-Key", this.Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<SchoolGeocoordinate>>("/api/v1/geocoordinates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV1GeocoordinatesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
