/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FranchiseePortal.LeadsWebApiClient.Client.OpenAPIDateConverter;

namespace FranchiseePortal.LeadsWebApiClient.Model
{
    /// <summary>
    /// Defines LevelOfInterest
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LevelOfInterest
    {
        /// <summary>
        /// Enum Asap for value: Asap
        /// </summary>
        [EnumMember(Value = "Asap")]
        Asap = 1,

        /// <summary>
        /// Enum SixMonths for value: SixMonths
        /// </summary>
        [EnumMember(Value = "SixMonths")]
        SixMonths = 2,

        /// <summary>
        /// Enum TwelveMonths for value: TwelveMonths
        /// </summary>
        [EnumMember(Value = "TwelveMonths")]
        TwelveMonths = 3,

        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 4

    }

}
