/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FranchiseePortal.LeadsWebApiClient.Client.OpenAPIDateConverter;

namespace FranchiseePortal.LeadsWebApiClient.Model
{
    /// <summary>
    /// TourLeadChildInput
    /// </summary>
    [DataContract(Name = "TourLeadChildInput")]
    public partial class TourLeadChildInput : IEquatable<TourLeadChildInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TourLeadChildInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TourLeadChildInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TourLeadChildInput" /> class.
        /// </summary>
        /// <param name="schoolChildLeadId">schoolChildLeadId.</param>
        /// <param name="firstName">firstName (required).</param>
        public TourLeadChildInput(long schoolChildLeadId = default(long), string firstName = default(string))
        {
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new ArgumentNullException("firstName is a required property for TourLeadChildInput and cannot be null");
            }
            this.FirstName = firstName;
            this.SchoolChildLeadId = schoolChildLeadId;
        }

        /// <summary>
        /// Gets or Sets SchoolChildLeadId
        /// </summary>
        [DataMember(Name = "schoolChildLeadId", EmitDefaultValue = false)]
        public long SchoolChildLeadId { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [DataMember(Name = "firstName", IsRequired = true, EmitDefaultValue = false)]
        public string FirstName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TourLeadChildInput {\n");
            sb.Append("  SchoolChildLeadId: ").Append(SchoolChildLeadId).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TourLeadChildInput);
        }

        /// <summary>
        /// Returns true if TourLeadChildInput instances are equal
        /// </summary>
        /// <param name="input">Instance of TourLeadChildInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TourLeadChildInput input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SchoolChildLeadId == input.SchoolChildLeadId ||
                    this.SchoolChildLeadId.Equals(input.SchoolChildLeadId)
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SchoolChildLeadId.GetHashCode();
                if (this.FirstName != null)
                {
                    hashCode = (hashCode * 59) + this.FirstName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
