/*
 * Goddard.FMS.SchoolEvents
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FranchiseePortal.SchoolEventsWebApiClient.Client.OpenAPIDateConverter;

namespace FranchiseePortal.SchoolEventsWebApiClient.Model
{
    /// <summary>
    /// PostEventTemplate
    /// </summary>
    [DataContract(Name = "PostEventTemplate")]
    public partial class PostEventTemplate : IEquatable<PostEventTemplate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostEventTemplate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PostEventTemplate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PostEventTemplate" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="version">version.</param>
        /// <param name="schoolID">schoolID (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="startTime">startTime.</param>
        /// <param name="endTime">endTime.</param>
        /// <param name="iconFileName">iconFileName.</param>
        /// <param name="publicWebsiteDescription">publicWebsiteDescription.</param>
        /// <param name="availableMonthsOfYear">availableMonthsOfYear.</param>
        public PostEventTemplate(long? id = default(long?), int version = default(int), long schoolID = default(long), string name = default(string), string startTime = default(string), string endTime = default(string), string iconFileName = default(string), string publicWebsiteDescription = default(string), int availableMonthsOfYear = default(int))
        {
            this.SchoolID = schoolID;
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name is a required property for PostEventTemplate and cannot be null");
            this.Id = id;
            this.Version = version;
            this.StartTime = startTime;
            this.EndTime = endTime;
            this.IconFileName = iconFileName;
            this.PublicWebsiteDescription = publicWebsiteDescription;
            this.AvailableMonthsOfYear = availableMonthsOfYear;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public int Version { get; set; }

        /// <summary>
        /// Gets or Sets SchoolID
        /// </summary>
        [DataMember(Name = "schoolID", IsRequired = true, EmitDefaultValue = false)]
        public long SchoolID { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [DataMember(Name = "startTime", EmitDefaultValue = true)]
        public string StartTime { get; set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        [DataMember(Name = "endTime", EmitDefaultValue = true)]
        public string EndTime { get; set; }

        /// <summary>
        /// Gets or Sets IconFileName
        /// </summary>
        [DataMember(Name = "iconFileName", EmitDefaultValue = true)]
        public string IconFileName { get; set; }

        /// <summary>
        /// Gets or Sets PublicWebsiteDescription
        /// </summary>
        [DataMember(Name = "publicWebsiteDescription", EmitDefaultValue = true)]
        public string PublicWebsiteDescription { get; set; }

        /// <summary>
        /// Gets or Sets AvailableMonthsOfYear
        /// </summary>
        [DataMember(Name = "availableMonthsOfYear", EmitDefaultValue = false)]
        public int AvailableMonthsOfYear { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PostEventTemplate {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  SchoolID: ").Append(SchoolID).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  IconFileName: ").Append(IconFileName).Append("\n");
            sb.Append("  PublicWebsiteDescription: ").Append(PublicWebsiteDescription).Append("\n");
            sb.Append("  AvailableMonthsOfYear: ").Append(AvailableMonthsOfYear).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PostEventTemplate);
        }

        /// <summary>
        /// Returns true if PostEventTemplate instances are equal
        /// </summary>
        /// <param name="input">Instance of PostEventTemplate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostEventTemplate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Version == input.Version ||
                    this.Version.Equals(input.Version)
                ) && 
                (
                    this.SchoolID == input.SchoolID ||
                    this.SchoolID.Equals(input.SchoolID)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.IconFileName == input.IconFileName ||
                    (this.IconFileName != null &&
                    this.IconFileName.Equals(input.IconFileName))
                ) && 
                (
                    this.PublicWebsiteDescription == input.PublicWebsiteDescription ||
                    (this.PublicWebsiteDescription != null &&
                    this.PublicWebsiteDescription.Equals(input.PublicWebsiteDescription))
                ) && 
                (
                    this.AvailableMonthsOfYear == input.AvailableMonthsOfYear ||
                    this.AvailableMonthsOfYear.Equals(input.AvailableMonthsOfYear)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                hashCode = hashCode * 59 + this.Version.GetHashCode();
                hashCode = hashCode * 59 + this.SchoolID.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.StartTime != null)
                    hashCode = hashCode * 59 + this.StartTime.GetHashCode();
                if (this.EndTime != null)
                    hashCode = hashCode * 59 + this.EndTime.GetHashCode();
                if (this.IconFileName != null)
                    hashCode = hashCode * 59 + this.IconFileName.GetHashCode();
                if (this.PublicWebsiteDescription != null)
                    hashCode = hashCode * 59 + this.PublicWebsiteDescription.GetHashCode();
                hashCode = hashCode * 59 + this.AvailableMonthsOfYear.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
