/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.LeadsWebApiClient.Api;
using FranchiseePortal.LeadsWebApiClient.Model;
using FranchiseePortal.LeadsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.LeadsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV1SchoolLeadsInternalPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1SchoolLeadsInternalPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV1SchoolLeadsInternalPostRequest
        //private ApiV1SchoolLeadsInternalPostRequest instance;

        public ApiV1SchoolLeadsInternalPostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiV1SchoolLeadsInternalPostRequest
            //instance = new ApiV1SchoolLeadsInternalPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV1SchoolLeadsInternalPostRequest
        /// </summary>
        [Fact]
        public void ApiV1SchoolLeadsInternalPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV1SchoolLeadsInternalPostRequest
            //Assert.IsType<ApiV1SchoolLeadsInternalPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'SchoolParentLeadId'
        /// </summary>
        [Fact]
        public void SchoolParentLeadIdTest()
        {
            // TODO unit test for the property 'SchoolParentLeadId'
        }
        /// <summary>
        /// Test the property 'SchoolId'
        /// </summary>
        [Fact]
        public void SchoolIdTest()
        {
            // TODO unit test for the property 'SchoolId'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'StreetLine1'
        /// </summary>
        [Fact]
        public void StreetLine1Test()
        {
            // TODO unit test for the property 'StreetLine1'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'ZipCode'
        /// </summary>
        [Fact]
        public void ZipCodeTest()
        {
            // TODO unit test for the property 'ZipCode'
        }
        /// <summary>
        /// Test the property 'MobilePhone'
        /// </summary>
        [Fact]
        public void MobilePhoneTest()
        {
            // TODO unit test for the property 'MobilePhone'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'ReferredBy'
        /// </summary>
        [Fact]
        public void ReferredByTest()
        {
            // TODO unit test for the property 'ReferredBy'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'ContactPreference'
        /// </summary>
        [Fact]
        public void ContactPreferenceTest()
        {
            // TODO unit test for the property 'ContactPreference'
        }
        /// <summary>
        /// Test the property 'SchoolChildLeads'
        /// </summary>
        [Fact]
        public void SchoolChildLeadsTest()
        {
            // TODO unit test for the property 'SchoolChildLeads'
        }
        /// <summary>
        /// Test the property 'AdditionalRemarks'
        /// </summary>
        [Fact]
        public void AdditionalRemarksTest()
        {
            // TODO unit test for the property 'AdditionalRemarks'
        }
        /// <summary>
        /// Test the property 'ProgramsOfInterest'
        /// </summary>
        [Fact]
        public void ProgramsOfInterestTest()
        {
            // TODO unit test for the property 'ProgramsOfInterest'
        }
        /// <summary>
        /// Test the property 'DaysOfInterest'
        /// </summary>
        [Fact]
        public void DaysOfInterestTest()
        {
            // TODO unit test for the property 'DaysOfInterest'
        }

    }

}
