/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.LeadsWebApiClient.Api;
using FranchiseePortal.LeadsWebApiClient.Model;
using FranchiseePortal.LeadsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.LeadsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV1ValidationPhonePostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1ValidationPhonePostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV1ValidationPhonePostRequest
        //private ApiV1ValidationPhonePostRequest instance;

        public ApiV1ValidationPhonePostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiV1ValidationPhonePostRequest
            //instance = new ApiV1ValidationPhonePostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV1ValidationPhonePostRequest
        /// </summary>
        [Fact]
        public void ApiV1ValidationPhonePostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV1ValidationPhonePostRequest
            //Assert.IsType<ApiV1ValidationPhonePostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

    }

}
