/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.LeadsWebApiClient.Api;
using FranchiseePortal.LeadsWebApiClient.Model;
using FranchiseePortal.LeadsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.LeadsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV1SchoolLeadsIdTourPutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1SchoolLeadsIdTourPutRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV1SchoolLeadsIdTourPutRequest
        //private ApiV1SchoolLeadsIdTourPutRequest instance;

        public ApiV1SchoolLeadsIdTourPutRequestTests()
        {
            // TODO uncomment below to create an instance of ApiV1SchoolLeadsIdTourPutRequest
            //instance = new ApiV1SchoolLeadsIdTourPutRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV1SchoolLeadsIdTourPutRequest
        /// </summary>
        [Fact]
        public void ApiV1SchoolLeadsIdTourPutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV1SchoolLeadsIdTourPutRequest
            //Assert.IsType<ApiV1SchoolLeadsIdTourPutRequest>(instance);
        }


        /// <summary>
        /// Test the property 'SchoolChildLeads'
        /// </summary>
        [Fact]
        public void SchoolChildLeadsTest()
        {
            // TODO unit test for the property 'SchoolChildLeads'
        }
        /// <summary>
        /// Test the property 'DaysOfInterest'
        /// </summary>
        [Fact]
        public void DaysOfInterestTest()
        {
            // TODO unit test for the property 'DaysOfInterest'
        }
        /// <summary>
        /// Test the property 'ProgramsOfInterest'
        /// </summary>
        [Fact]
        public void ProgramsOfInterestTest()
        {
            // TODO unit test for the property 'ProgramsOfInterest'
        }
        /// <summary>
        /// Test the property 'TourQuestions'
        /// </summary>
        [Fact]
        public void TourQuestionsTest()
        {
            // TODO unit test for the property 'TourQuestions'
        }

    }

}
