/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.LeadsWebApiClient.Api;
using FranchiseePortal.LeadsWebApiClient.Model;
using FranchiseePortal.LeadsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.LeadsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DaysOfInterest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DaysOfInterestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DaysOfInterest
        //private DaysOfInterest instance;

        public DaysOfInterestTests()
        {
            // TODO uncomment below to create an instance of DaysOfInterest
            //instance = new DaysOfInterest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DaysOfInterest
        /// </summary>
        [Fact]
        public void DaysOfInterestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DaysOfInterest
            //Assert.IsType<DaysOfInterest>(instance);
        }



    }

}
