/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.LeadsWebApiClient.Api;
using FranchiseePortal.LeadsWebApiClient.Model;
using FranchiseePortal.LeadsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.LeadsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing EmailValidationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailValidationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailValidationDto
        //private EmailValidationDto instance;

        public EmailValidationDtoTests()
        {
            // TODO uncomment below to create an instance of EmailValidationDto
            //instance = new EmailValidationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailValidationDto
        /// </summary>
        [Fact]
        public void EmailValidationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailValidationDto
            //Assert.IsType<EmailValidationDto>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
