/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.LeadsWebApiClient.Api;
using FranchiseePortal.LeadsWebApiClient.Model;
using FranchiseePortal.LeadsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.LeadsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PhoneValidationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhoneValidationResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhoneValidationResult
        //private PhoneValidationResult instance;

        public PhoneValidationResultTests()
        {
            // TODO uncomment below to create an instance of PhoneValidationResult
            //instance = new PhoneValidationResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhoneValidationResult
        /// </summary>
        [Fact]
        public void PhoneValidationResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhoneValidationResult
            //Assert.IsType<PhoneValidationResult>(instance);
        }


        /// <summary>
        /// Test the property 'Rejection'
        /// </summary>
        [Fact]
        public void RejectionTest()
        {
            // TODO unit test for the property 'Rejection'
        }
        /// <summary>
        /// Test the property 'PhoneType'
        /// </summary>
        [Fact]
        public void PhoneTypeTest()
        {
            // TODO unit test for the property 'PhoneType'
        }
        /// <summary>
        /// Test the property 'ProviderResult'
        /// </summary>
        [Fact]
        public void ProviderResultTest()
        {
            // TODO unit test for the property 'ProviderResult'
        }
        /// <summary>
        /// Test the property 'FormattedPhoneNumber'
        /// </summary>
        [Fact]
        public void FormattedPhoneNumberTest()
        {
            // TODO unit test for the property 'FormattedPhoneNumber'
        }
        /// <summary>
        /// Test the property 'ConfidenceLevel'
        /// </summary>
        [Fact]
        public void ConfidenceLevelTest()
        {
            // TODO unit test for the property 'ConfidenceLevel'
        }

    }

}
