/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.LeadsWebApiClient.Api;
using FranchiseePortal.LeadsWebApiClient.Model;
using FranchiseePortal.LeadsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.LeadsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TourLeadChildInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TourLeadChildInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TourLeadChildInput
        //private TourLeadChildInput instance;

        public TourLeadChildInputTests()
        {
            // TODO uncomment below to create an instance of TourLeadChildInput
            //instance = new TourLeadChildInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TourLeadChildInput
        /// </summary>
        [Fact]
        public void TourLeadChildInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" TourLeadChildInput
            //Assert.IsType<TourLeadChildInput>(instance);
        }


        /// <summary>
        /// Test the property 'SchoolChildLeadId'
        /// </summary>
        [Fact]
        public void SchoolChildLeadIdTest()
        {
            // TODO unit test for the property 'SchoolChildLeadId'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

    }

}
