/*
 * Goddard.AuthorizationApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.AuthorizationWebApiClient.Api;
using FranchiseePortal.AuthorizationWebApiClient.Model;
using FranchiseePortal.AuthorizationWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.AuthorizationWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AuthorizedSchool
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthorizedSchoolTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthorizedSchool
        //private AuthorizedSchool instance;

        public AuthorizedSchoolTests()
        {
            // TODO uncomment below to create an instance of AuthorizedSchool
            //instance = new AuthorizedSchool();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthorizedSchool
        /// </summary>
        [Fact]
        public void AuthorizedSchoolInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthorizedSchool
            //Assert.IsType<AuthorizedSchool>(instance);
        }


        /// <summary>
        /// Test the property 'CrmId'
        /// </summary>
        [Fact]
        public void CrmIdTest()
        {
            // TODO unit test for the property 'CrmId'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
