/*
 * Goddard.FMS.SchoolTestimonials
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.TestimonialsWebApiClient.Api;
using FranchiseePortal.TestimonialsWebApiClient.Model;
using FranchiseePortal.TestimonialsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.TestimonialsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing GetUnpublishedTestimonialResultPagedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetUnpublishedTestimonialResultPagedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetUnpublishedTestimonialResultPagedResponse
        //private GetUnpublishedTestimonialResultPagedResponse instance;

        public GetUnpublishedTestimonialResultPagedResponseTests()
        {
            // TODO uncomment below to create an instance of GetUnpublishedTestimonialResultPagedResponse
            //instance = new GetUnpublishedTestimonialResultPagedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetUnpublishedTestimonialResultPagedResponse
        /// </summary>
        [Fact]
        public void GetUnpublishedTestimonialResultPagedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetUnpublishedTestimonialResultPagedResponse
            //Assert.IsType<GetUnpublishedTestimonialResultPagedResponse>(instance);
        }


        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
