/*
 * Goddard.FMS.SchoolEvents
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.SchoolEventsWebApiClient.Api;
using FranchiseePortal.SchoolEventsWebApiClient.Model;
using FranchiseePortal.SchoolEventsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.SchoolEventsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PostEventTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostEventTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostEventTemplate
        //private PostEventTemplate instance;

        public PostEventTemplateTests()
        {
            // TODO uncomment below to create an instance of PostEventTemplate
            //instance = new PostEventTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostEventTemplate
        /// </summary>
        [Fact]
        public void PostEventTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostEventTemplate
            //Assert.IsType<PostEventTemplate>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'SchoolID'
        /// </summary>
        [Fact]
        public void SchoolIDTest()
        {
            // TODO unit test for the property 'SchoolID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'IconFileName'
        /// </summary>
        [Fact]
        public void IconFileNameTest()
        {
            // TODO unit test for the property 'IconFileName'
        }
        /// <summary>
        /// Test the property 'PublicWebsiteDescription'
        /// </summary>
        [Fact]
        public void PublicWebsiteDescriptionTest()
        {
            // TODO unit test for the property 'PublicWebsiteDescription'
        }
        /// <summary>
        /// Test the property 'AvailableMonthsOfYear'
        /// </summary>
        [Fact]
        public void AvailableMonthsOfYearTest()
        {
            // TODO unit test for the property 'AvailableMonthsOfYear'
        }

    }

}
