/*
 * Goddard School Features API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.FeaturesWebApiClient.Api;
using FranchiseePortal.FeaturesWebApiClient.Model;
using FranchiseePortal.FeaturesWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.FeaturesWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AddFeatureModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddFeatureModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddFeatureModel
        //private AddFeatureModel instance;

        public AddFeatureModelTests()
        {
            // TODO uncomment below to create an instance of AddFeatureModel
            //instance = new AddFeatureModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddFeatureModel
        /// </summary>
        [Fact]
        public void AddFeatureModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddFeatureModel
            //Assert.IsType<AddFeatureModel>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
