/*
 * Goddard School Features API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.FeaturesWebApiClient.Api;
using FranchiseePortal.FeaturesWebApiClient.Model;
using FranchiseePortal.FeaturesWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.FeaturesWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SchoolFeaturesModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchoolFeaturesModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchoolFeaturesModel
        //private SchoolFeaturesModel instance;

        public SchoolFeaturesModelTests()
        {
            // TODO uncomment below to create an instance of SchoolFeaturesModel
            //instance = new SchoolFeaturesModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchoolFeaturesModel
        /// </summary>
        [Fact]
        public void SchoolFeaturesModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchoolFeaturesModel
            //Assert.IsType<SchoolFeaturesModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SchoolNumber'
        /// </summary>
        [Fact]
        public void SchoolNumberTest()
        {
            // TODO unit test for the property 'SchoolNumber'
        }
        /// <summary>
        /// Test the property 'SchoolId'
        /// </summary>
        [Fact]
        public void SchoolIdTest()
        {
            // TODO unit test for the property 'SchoolId'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'TransportationStops'
        /// </summary>
        [Fact]
        public void TransportationStopsTest()
        {
            // TODO unit test for the property 'TransportationStops'
        }

    }

}
