/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FranchiseePortal.ContentWebApiClient.Client.OpenAPIDateConverter;

namespace FranchiseePortal.ContentWebApiClient.Model
{
    /// <summary>
    /// SchoolsUpdateRequest
    /// </summary>
    [DataContract(Name = "SchoolsUpdateRequest")]
    public partial class SchoolsUpdateRequest : IEquatable<SchoolsUpdateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SchoolsUpdateRequest" /> class.
        /// </summary>
        /// <param name="heroImage">heroImage.</param>
        /// <param name="iconCardsJson">iconCardsJson.</param>
        public SchoolsUpdateRequest(string heroImage = default(string), string iconCardsJson = default(string))
        {
            this.HeroImage = heroImage;
            this.IconCardsJson = iconCardsJson;
        }

        /// <summary>
        /// Gets or Sets HeroImage
        /// </summary>
        [DataMember(Name = "heroImage", EmitDefaultValue = true)]
        public string HeroImage { get; set; }

        /// <summary>
        /// Gets or Sets IconCardsJson
        /// </summary>
        [DataMember(Name = "iconCardsJson", EmitDefaultValue = true)]
        public string IconCardsJson { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SchoolsUpdateRequest {\n");
            sb.Append("  HeroImage: ").Append(HeroImage).Append("\n");
            sb.Append("  IconCardsJson: ").Append(IconCardsJson).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SchoolsUpdateRequest);
        }

        /// <summary>
        /// Returns true if SchoolsUpdateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SchoolsUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SchoolsUpdateRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.HeroImage == input.HeroImage ||
                    (this.HeroImage != null &&
                    this.HeroImage.Equals(input.HeroImage))
                ) && 
                (
                    this.IconCardsJson == input.IconCardsJson ||
                    (this.IconCardsJson != null &&
                    this.IconCardsJson.Equals(input.IconCardsJson))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HeroImage != null)
                {
                    hashCode = (hashCode * 59) + this.HeroImage.GetHashCode();
                }
                if (this.IconCardsJson != null)
                {
                    hashCode = (hashCode * 59) + this.IconCardsJson.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
