/*
 * Goddard.ToursWebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FranchiseePortal.ToursWebApiClient.Client;
using FranchiseePortal.ToursWebApiClient.Api;
// uncomment below to import models
//using FranchiseePortal.ToursWebApiClient.Model;

namespace FranchiseePortal.ToursWebApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing AvailabilityApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AvailabilityApiTests : IDisposable
    {
        private AvailabilityApi instance;

        public AvailabilityApiTests()
        {
            instance = new AvailabilityApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailabilityApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AvailabilityApi
            //Assert.IsType<AvailabilityApi>(instance);
        }

        /// <summary>
        /// Test ApiV1SchoolsSchoolIdAvailabilityGet
        /// </summary>
        [Fact]
        public void ApiV1SchoolsSchoolIdAvailabilityGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string schoolId = null;
            //var response = instance.ApiV1SchoolsSchoolIdAvailabilityGet(schoolId);
            //Assert.IsType<AvailabilityDto>(response);
        }

        /// <summary>
        /// Test ApiV1SchoolsSchoolIdAvailabilityPut
        /// </summary>
        [Fact]
        public void ApiV1SchoolsSchoolIdAvailabilityPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string schoolId = null;
            //AvailabilityDto availabilityDto = null;
            //var response = instance.ApiV1SchoolsSchoolIdAvailabilityPut(schoolId, availabilityDto);
            //Assert.IsType<AvailabilityDto>(response);
        }
    }
}
