/*
 * Goddard.ToursWebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FranchiseePortal.ToursWebApiClient.Client;
using FranchiseePortal.ToursWebApiClient.Api;
// uncomment below to import models
//using FranchiseePortal.ToursWebApiClient.Model;

namespace FranchiseePortal.ToursWebApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing SchedulesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SchedulesApiTests : IDisposable
    {
        private SchedulesApi instance;

        public SchedulesApiTests()
        {
            instance = new SchedulesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchedulesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SchedulesApi
            //Assert.IsType<SchedulesApi>(instance);
        }

        /// <summary>
        /// Test ApiV1SchoolsSchoolIdSchedulesGet
        /// </summary>
        [Fact]
        public void ApiV1SchoolsSchoolIdSchedulesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string schoolId = null;
            //DateTime startDate = null;
            //DateTime endDate = null;
            //var response = instance.ApiV1SchoolsSchoolIdSchedulesGet(schoolId, startDate, endDate);
            //Assert.IsType<List<ScheduleDto>>(response);
        }
    }
}
