/*
 * Goddard.ToursWebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FranchiseePortal.ToursWebApiClient.Client.OpenAPIDateConverter;

namespace FranchiseePortal.ToursWebApiClient.Model
{
    /// <summary>
    /// Defines TourSort
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TourSort
    {
        /// <summary>
        /// Enum Default for value: Default
        /// </summary>
        [EnumMember(Value = "Default")]
        Default = 1,

        /// <summary>
        /// Enum StartDateTime for value: StartDateTime
        /// </summary>
        [EnumMember(Value = "StartDateTime")]
        StartDateTime = 2,

        /// <summary>
        /// Enum Type for value: Type
        /// </summary>
        [EnumMember(Value = "Type")]
        Type = 3,

        /// <summary>
        /// Enum LeadFirstName for value: LeadFirstName
        /// </summary>
        [EnumMember(Value = "LeadFirstName")]
        LeadFirstName = 4,

        /// <summary>
        /// Enum LeadLastName for value: LeadLastName
        /// </summary>
        [EnumMember(Value = "LeadLastName")]
        LeadLastName = 5,

        /// <summary>
        /// Enum TourGuide for value: TourGuide
        /// </summary>
        [EnumMember(Value = "TourGuide")]
        TourGuide = 6

    }

}
