/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CompleteUploadResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompleteUploadResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompleteUploadResponse
        //private CompleteUploadResponse instance;

        public CompleteUploadResponseTests()
        {
            // TODO uncomment below to create an instance of CompleteUploadResponse
            //instance = new CompleteUploadResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompleteUploadResponse
        /// </summary>
        [Fact]
        public void CompleteUploadResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompleteUploadResponse
            //Assert.IsType<CompleteUploadResponse>(instance);
        }


        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

    }

}
