/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing FileUploadToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileUploadTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileUploadToken
        //private FileUploadToken instance;

        public FileUploadTokenTests()
        {
            // TODO uncomment below to create an instance of FileUploadToken
            //instance = new FileUploadToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileUploadToken
        /// </summary>
        [Fact]
        public void FileUploadTokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileUploadToken
            //Assert.IsType<FileUploadToken>(instance);
        }


        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'MinPartSize'
        /// </summary>
        [Fact]
        public void MinPartSizeTest()
        {
            // TODO unit test for the property 'MinPartSize'
        }
        /// <summary>
        /// Test the property 'MaxPartSize'
        /// </summary>
        [Fact]
        public void MaxPartSizeTest()
        {
            // TODO unit test for the property 'MaxPartSize'
        }
        /// <summary>
        /// Test the property 'UploadUris'
        /// </summary>
        [Fact]
        public void UploadUrisTest()
        {
            // TODO unit test for the property 'UploadUris'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Fact]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'UploadToken'
        /// </summary>
        [Fact]
        public void UploadTokenTest()
        {
            // TODO unit test for the property 'UploadToken'
        }

    }

}
