/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ImageCardDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageCardDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageCardDto
        //private ImageCardDto instance;

        public ImageCardDtoTests()
        {
            // TODO uncomment below to create an instance of ImageCardDto
            //instance = new ImageCardDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageCardDto
        /// </summary>
        [Fact]
        public void ImageCardDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageCardDto
            //Assert.IsType<ImageCardDto>(instance);
        }


        /// <summary>
        /// Test the property 'BackgroundColor'
        /// </summary>
        [Fact]
        public void BackgroundColorTest()
        {
            // TODO unit test for the property 'BackgroundColor'
        }
        /// <summary>
        /// Test the property 'CqpropertyInheritanceCancelled'
        /// </summary>
        [Fact]
        public void CqpropertyInheritanceCancelledTest()
        {
            // TODO unit test for the property 'CqpropertyInheritanceCancelled'
        }
        /// <summary>
        /// Test the property 'FileReference'
        /// </summary>
        [Fact]
        public void FileReferenceTest()
        {
            // TODO unit test for the property 'FileReference'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'ImageLayout'
        /// </summary>
        [Fact]
        public void ImageLayoutTest()
        {
            // TODO unit test for the property 'ImageLayout'
        }
        /// <summary>
        /// Test the property 'LinkText'
        /// </summary>
        [Fact]
        public void LinkTextTest()
        {
            // TODO unit test for the property 'LinkText'
        }
        /// <summary>
        /// Test the property 'OpenInNewTab'
        /// </summary>
        [Fact]
        public void OpenInNewTabTest()
        {
            // TODO unit test for the property 'OpenInNewTab'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SortOverride'
        /// </summary>
        [Fact]
        public void SortOverrideTest()
        {
            // TODO unit test for the property 'SortOverride'
        }
        /// <summary>
        /// Test the property 'TargetUrl'
        /// </summary>
        [Fact]
        public void TargetUrlTest()
        {
            // TODO unit test for the property 'TargetUrl'
        }
        /// <summary>
        /// Test the property 'TextLayout'
        /// </summary>
        [Fact]
        public void TextLayoutTest()
        {
            // TODO unit test for the property 'TextLayout'
        }

    }

}
