/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing InitiateUploadResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitiateUploadResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitiateUploadResponse
        //private InitiateUploadResponse instance;

        public InitiateUploadResponseTests()
        {
            // TODO uncomment below to create an instance of InitiateUploadResponse
            //instance = new InitiateUploadResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitiateUploadResponse
        /// </summary>
        [Fact]
        public void InitiateUploadResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitiateUploadResponse
            //Assert.IsType<InitiateUploadResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Affinity'
        /// </summary>
        [Fact]
        public void AffinityTest()
        {
            // TODO unit test for the property 'Affinity'
        }
        /// <summary>
        /// Test the property 'FolderPath'
        /// </summary>
        [Fact]
        public void FolderPathTest()
        {
            // TODO unit test for the property 'FolderPath'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }
        /// <summary>
        /// Test the property 'CompleteUri'
        /// </summary>
        [Fact]
        public void CompleteUriTest()
        {
            // TODO unit test for the property 'CompleteUri'
        }

    }

}
