/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Link
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Link
        //private Link instance;

        public LinkTests()
        {
            // TODO uncomment below to create an instance of Link
            //instance = new Link();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Link
        /// </summary>
        [Fact]
        public void LinkInstanceTest()
        {
            // TODO uncomment below to test "IsType" Link
            //Assert.IsType<Link>(instance);
        }


        /// <summary>
        /// Test the property 'Rel'
        /// </summary>
        [Fact]
        public void RelTest()
        {
            // TODO unit test for the property 'Rel'
        }
        /// <summary>
        /// Test the property 'Class'
        /// </summary>
        [Fact]
        public void ClassTest()
        {
            // TODO unit test for the property 'Class'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Fact]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
