/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SummerCampListItemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SummerCampListItemDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SummerCampListItemDto
        //private SummerCampListItemDto instance;

        public SummerCampListItemDtoTests()
        {
            // TODO uncomment below to create an instance of SummerCampListItemDto
            //instance = new SummerCampListItemDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SummerCampListItemDto
        /// </summary>
        [Fact]
        public void SummerCampListItemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SummerCampListItemDto
            //Assert.IsType<SummerCampListItemDto>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Fact]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'FileReference'
        /// </summary>
        [Fact]
        public void FileReferenceTest()
        {
            // TODO unit test for the property 'FileReference'
        }
        /// <summary>
        /// Test the property 'Offtime'
        /// </summary>
        [Fact]
        public void OfftimeTest()
        {
            // TODO unit test for the property 'Offtime'
        }
        /// <summary>
        /// Test the property 'SortOverride'
        /// </summary>
        [Fact]
        public void SortOverrideTest()
        {
            // TODO unit test for the property 'SortOverride'
        }

    }

}
