/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TextComponentUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TextComponentUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TextComponentUpdateDto
        //private TextComponentUpdateDto instance;

        public TextComponentUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of TextComponentUpdateDto
            //instance = new TextComponentUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TextComponentUpdateDto
        /// </summary>
        [Fact]
        public void TextComponentUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TextComponentUpdateDto
            //Assert.IsType<TextComponentUpdateDto>(instance);
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

    }

}
