/*
 * Goddard.ContentWebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.ContentWebApiClient.Api;
using FranchiseePortal.ContentWebApiClient.Model;
using FranchiseePortal.ContentWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.ContentWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TitleComponentUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TitleComponentUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TitleComponentUpdateDto
        //private TitleComponentUpdateDto instance;

        public TitleComponentUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of TitleComponentUpdateDto
            //instance = new TitleComponentUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TitleComponentUpdateDto
        /// </summary>
        [Fact]
        public void TitleComponentUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TitleComponentUpdateDto
            //Assert.IsType<TitleComponentUpdateDto>(instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
