/*
 * Goddard iPaaS Leads API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FranchiseePortal.LeadsWebApiClient.Client;
using FranchiseePortal.LeadsWebApiClient.Api;
// uncomment below to import models
//using FranchiseePortal.LeadsWebApiClient.Model;

namespace FranchiseePortal.LeadsWebApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing SchoolParentLeadsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SchoolParentLeadsApiTests : IDisposable
    {
        private SchoolParentLeadsApi instance;

        public SchoolParentLeadsApiTests()
        {
            instance = new SchoolParentLeadsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchoolParentLeadsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SchoolParentLeadsApi
            //Assert.IsType<SchoolParentLeadsApi>(instance);
        }

        /// <summary>
        /// Test ApiV1SchoolLeadsPost
        /// </summary>
        [Fact]
        public void ApiV1SchoolLeadsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Lead lead = null;
            //var response = instance.ApiV1SchoolLeadsPost(lead);
            //Assert.IsType<Lead>(response);
        }

        /// <summary>
        /// Test ApiV1SchoolLeadsSchoolIdQGet
        /// </summary>
        [Fact]
        public void ApiV1SchoolLeadsSchoolIdQGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long schoolId = null;
            //string q = null;
            //var response = instance.ApiV1SchoolLeadsSchoolIdQGet(schoolId, q);
            //Assert.IsType<List<LeadDto>>(response);
        }
    }
}
