/*
 * Goddard iPaaS Schools API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.SchoolsWebApiClient.Api;
using FranchiseePortal.SchoolsWebApiClient.Model;
using FranchiseePortal.SchoolsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.SchoolsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SchoolFeature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchoolFeatureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchoolFeature
        //private SchoolFeature instance;

        public SchoolFeatureTests()
        {
            // TODO uncomment below to create an instance of SchoolFeature
            //instance = new SchoolFeature();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchoolFeature
        /// </summary>
        [Fact]
        public void SchoolFeatureInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchoolFeature
            //Assert.IsType<SchoolFeature>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CrmSchoolId'
        /// </summary>
        [Fact]
        public void CrmSchoolIdTest()
        {
            // TODO unit test for the property 'CrmSchoolId'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'FeatureName'
        /// </summary>
        [Fact]
        public void FeatureNameTest()
        {
            // TODO unit test for the property 'FeatureName'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Stops'
        /// </summary>
        [Fact]
        public void StopsTest()
        {
            // TODO unit test for the property 'Stops'
        }

    }

}
