/*
 * Goddard iPaaS Schools API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FranchiseePortal.SchoolsWebApiClient.Api;
using FranchiseePortal.SchoolsWebApiClient.Model;
using FranchiseePortal.SchoolsWebApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FranchiseePortal.SchoolsWebApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TransportationStop
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransportationStopTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransportationStop
        //private TransportationStop instance;

        public TransportationStopTests()
        {
            // TODO uncomment below to create an instance of TransportationStop
            //instance = new TransportationStop();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransportationStop
        /// </summary>
        [Fact]
        public void TransportationStopInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransportationStop
            //Assert.IsType<TransportationStop>(instance);
        }


        /// <summary>
        /// Test the property 'Num'
        /// </summary>
        [Fact]
        public void NumTest()
        {
            // TODO unit test for the property 'Num'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
